### ISSUE TITLE
No possibility to pipe from stdout.

### ISSUE THREAD

**Issue by txdv** [shubhamchaudhary/gistit#2]
Something like 

```
echo "TEST" | gistit
```

would allow me to pass debug information right into a gist

**Comment by shubhamchaudhary** [comment]
Hi, this feature has been implemented in v0.0.3. 
Thanks a lot for taking the time to suggest this feature.

**Comment by shubhamchaudhary** [comment]
I am closing this issue for now. Please feel free to get in touch if needed :)
